.Dd $Mdocdate$
.Dt libdsbmime 3
.Sh NAME
.Nm libdsbmime
.Nd "Library to determine file types"
.Sh SYNOPSIS
.In dsbmime.h
.Ft int
.Fn dsbmime_init "void"
.Ft char *
.Fn dsbmime_get_type "const char *file"
.Ft void
.Fn dsbmime_cleanup "void"
.Sh DESCRIPTION
.Nm
is a C library to identify a file's MIME type by using
freedesktop.org's Shared MIME database package.
.Pp
Before using any other function of the library,
.Fn dsbmime_init
must be called. The function
.Fn dsbmime_get_type
returns the MIME type of the given
.Em file
as a string stored in a static buffer. Subsequent calls
to the same function will modify that buffer. In order to free memory used
by the library, the function
.Fn dsbmime_cleanup
can be called.
.Sh RETURN VALUES
.Fn dsbmime_init
returns -1 if an error has occurred, else 0.
.Fn dsbmime_get_type
returns a pointer to a string containing the
.Em file Ns 's
MIME type, or
.Dv NULL
if the file type could not be determined. If
an error has occurred,
.Dv NULL
is returned and
.Em errno
is set.
.Sh INSTALLATION
.Bd -literal
# make install
.Ed
.Pp
or if you're not happy with the predefined PREFIX:
.Bd -literal
# make PREFIX=/somewhere/else install
.Ed
.Ss DEPENDENCIES
.Nm
needs freedsktop.org's Shared MIME database package.
.Sh INSTALLED FILES
.Bl -tag -width ${PREFIX}/man/man3/libdsbmime.3.gz -compact
.It Pa ${PREFIX}/include/dsbmime.h
Include file
.It Pa ${PREFIX}/lib/libdsbmime.a
Static library file
.It Pa ${PREFIX}/man/man3/libdsbmime.3.gz
Manunal page
.El
.Sh EXAMPLES
See
.Em test.c

